### ISSUE TITLE
Fehlermeldung 

### ISSUE THREAD

**Issue by T0biii** [T0biii/TeamSpeakIp#5]
LuciDuki
HI.
Ich bekomme immer folgende Fehlermeldung wenn ich einen Befehl vom Plugin ausführe:
`
[11:56:42] [Server thread/INFO]: L_D issued server command: /ts [11:56:42] [Server thread/WARN]: java.lang.NullPointerException [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendTimings(TitleManager.java:83) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendTitles(TitleManager.java:33) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.commands.ts.onCommand(ts.java:189) [11:56:42] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [11:56:42] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [11:56:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [11:56:42] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [11:56:42] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [11:56:42] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745) [11:56:42] [Server thread/WARN]: java.lang.NullPointerException [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendTitle(TitleManager.java:48) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendTitles(TitleManager.java:34) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.commands.ts.onCommand(ts.java:189) [11:56:42] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [11:56:42] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [11:56:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [11:56:42] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [11:56:42] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [11:56:42] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745) [11:56:42] [Server thread/WARN]: java.lang.NullPointerException [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendSubTitle(TitleManager.java:68) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.Methods.TitleManager.sendTitles(TitleManager.java:35) [11:56:42] [Server thread/WARN]: at me.itztobi.ts.commands.ts.onCommand(ts.java:189) [11:56:42] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [11:56:42] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [11:56:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [11:56:42] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [11:56:42] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [11:56:42] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [11:56:42] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)`

Ich nutze Spigot 1.8.8 Pluginversion 3.7.1 habs auch mit älteren versucht und hat nicht funktioniert.

**Comment by T0biii** [comment]
https://dev.bukkit.org/projects/teamspeak-ip/files/2363064
Maybed Fixed Version
